dist: xenial
services:
  - xvfb
env:
  global:
    - PYTEST_ADDOPTS="--verbose --instafail"
    - FF_ESR_BINARY=$HOME/firefox-52.9.0esr/firefox/firefox-bin
    - FF_NIGHTLY_BINARY=$HOME/firefox-latest-nightly/firefox/firefox-bin
git:
  depth: 10
addons:
  sonarcloud:
    organization: "seleniumhq"

_bindings:
  java: &java
    language: java
    jdk: openjdk11
    if: env(BUILD_ONLY) IS NOT present || env(BUILD_ONLY) =~ /java/
  python: &python
    language: python
    python: "2.7"
    jdk: openjdk11
    if: env(BUILD_ONLY) IS NOT present || env(BUILD_ONLY) =~ /python/
  ruby: &ruby
    language: ruby
    rvm: 2.5
    jdk: openjdk11
    if: env(BUILD_ONLY) IS NOT present || env(BUILD_ONLY) =~ /ruby/
  node: &node
    language: node_js
    node_js: node
    if: env(BUILD_ONLY) IS NOT present || env(BUILD_ONLY) =~ /node/

_browsers:
  firefox: &firefox-latest
    addons:
      firefox: latest
  firefox-esr: &firefox-esr
    addons:
      firefox: "52.9.0esr"
  firefox-nightly: &firefox-nightly
    addons:
      firefox: latest-nightly
  chrome: &chrome
    addons:
      apt:
        packages:
          - google-chrome-stable

cache:
  directories:
    - $HOME/.cache/bazel-repo
    - $HOME/.cache/bazel-disk
    - build

matrix:
  include:
    - env: BZL="build --profile=/tmp/bazelprofile //java/client/..."
      <<: *java
install: ./scripts/travis/install.sh
before_script: ./scripts/travis/before_script.sh
script: travis_wait 60 ./scripts/travis/script.sh

notifications:
  email: false
  irc:
    channels:
      - secure: K+Wuro8Y/66zt9truTZuZzFmPqiGrFsH/sPzOBDK3+57mL6/vg2NoQCXOTq3U5RLdVKavlvZcm6+9nsNncVPRgzL7ORuW3BgLaBJis3lTA13AqlOnAbXcYytQEulVeWmvPipHFFFqaHs/z77lxm4fKwAAuBnK1f+mXKZDZR2hLo=
    on_success: never
    on_failure: always
    use_notice: true
    skip_join: true
  webhooks:
    urls:
      - secure: "T889SmDnNCj0fJeWkiX0TumHCnjowxpj5VoauVdTXyXT2R3Grjc6WPReQKw8qzQLxyvHWAip23RlYo2+bM5+zUz11jhQej5W+rk7et6AhVaz3UJiWDIqqaWBgQaB5RsbWzdBJTGukqv88Y0iCT4XHaXvY2stV7OxvkVg7wtQVSQ="
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
